spring:
  jpa:
    hibernate:
      ddl-auto: update  # ddl : data definition language, 자동으로 테이블 생성 및 수정 여부
  datasource:
    url: jdbc:mysql://localhost:3306/shop #?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 385291Zion!
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
    defer-datasource-initialization: true